name: Validação Deepchecks

on:
  push:
    paths:
      - 'models/saved_models/**'

jobs:
  deepchecks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'

    - name: Instalar dependências
      run: |
        pip install --upgrade pip
        pip install -r requirements-github.txt

    - name: Rodar validação com Deepchecks
      run: |
        python models/test_models/main.py

    - name: Upload do relatório
      uses: actions/upload-artifact@main
      with:
        name: validation-report
        path: validation_report.html
