name: Validação Deepchecks

on:
  push:

jobs:
  deepchecks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build da imagem Docker com cache
      run: |
        docker build \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache \
          -t deepchecks-validator dockerfile

    - name: Rodar validação com modelos e imagens montadas
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/models/saved_models:/models \
          -v ${{ github.workspace }}/datasets/soja_images:/imagens \
          deepchecks-validator
          
    - name: Upload do relatório
      uses: actions/upload-artifact@v3
      with:
        name: validation-report
        path: validation_report.html
